const assert = require('assert')
const algo = require('./1337')
console.log(algo('ELITE'))
assert(algo('ELITE') === '37173')
assert(algo('Code Chrysalis') === 'C0de C4rysa1is')
assert(algo('ZEHITOMO') === '23H170m0')
